---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eva.fullname" . }}-ai
  labels:
    {{- include "eva.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ai.replicaCount }}
  revisionHistoryLimit: {{ .Values.ai.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "eva.selectorLabels" . | nindent 6 }}
      {{- include "eva.ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eva.selectorLabels" . | nindent 8 }}
        {{- include "eva.ai.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.ai.podAnnotations | nindent 8 }}
    spec:
    {{- with .Values.ai.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "eva.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ai.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-ai-migrate-db
          image: {{ .Values.ai.image.repository }}:{{ default "latest" .Values.ai.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.ai.image.imagePullPolicy }}
          command: [ "sh", "-c" ]
          args: [
            "npm run migration:run"
          ]
      containers:
        - name: {{ .Chart.Name }}-ai
          securityContext:
            {{- toYaml .Values.ai.securityContext | nindent 12 }}
          image: {{ .Values.ai.image.repository }}:{{ default "latest" .Values.ai.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.ai.image.imagePullPolicy }}
          env:
            - name: PORT
              value: {{ default "80" .Values.ai.service.port | quote }}
            {{- with .Values.ai.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
    {{- with .Values.ai.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
    {{- end }}
          ports:
            - name: http
              containerPort: {{ default 80 .Values.ai.service.port }} 
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.ai.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ai.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.ai.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ai.resources | nindent 12 }}
      {{- with .Values.ai.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ai.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ai.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ai.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}
