---

apiVersion: v2
name: eva
version: 0.0.33
AppVersion: 0.1.0
description: The most open and well playful gallery with NFT and AI support in the web.
keywords:
  - gallery
  - NFT
  - AI
  - art
  - exhibition

type: application
dependencies:
  - name: postgresql
    version: 16.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: timescaledb-single
    version: 0.33.7
    repository: https://charts.fairwinds.com/incubator
    condition: timescaledb-single.enabled
    alias: timescaledb
home: https://evagallery.eu
icon: https://evagallery.eu/logo.jpg
sources:
  - https://github.com/eva-gallery/helm-chart
maintainers:
  - name: Teebor Choka
    email: teebor@choka.com
    url: https://github.com/Teebor-Choka
engine: gotpl
