---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eva.fullname" .}}-frontend
  labels: {{- include "eva.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.frontend.service.type}}
  {{- if eq .Values.frontend.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ default "80" .Values.frontend.service.port}}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ default "443" .Values.frontend.service.httpsPort}}
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "eva.selectorLabels" . | nindent 4}}
    {{- include "eva.frontend.selectorLabels" . | nindent 4}}
