---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eva.fullname" . }}-frontend
  labels:
    {{- include "eva.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: {{ .Values.frontend.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "eva.selectorLabels" . | nindent 6 }}
      {{- include "eva.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eva.selectorLabels" . | nindent 8 }}
        {{- include "eva.frontend.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.frontend.podAnnotations | nindent 8 }}
    spec:
    {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "eva.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: {{ .Values.frontend.image.repository }}:{{ default "latest" .Values.frontend.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.frontend.image.imagePullPolicy }}
          command: ["node"]
          args: ["server.js"]
          env:
            - name: HA_ACTIVE
              value: {{ .Values.frontend.replicaCount | int | ge 2 | quote }}
            - name: NEXT_PUBLIC_BACKEND_URL
            {{- if .Values.frontend.config.public_backend_url }}
              value: {{ .Values.frontend.config.public_backend_url }} 
            {{- else }}
              value: http://{{ include "eva.fullname" .}}-backend.{{ .Release.Namespace }}:80
            {{- end }}
            - name: INTERNAL_BACKEND_URL
              value: http://{{ include "eva.fullname" .}}-backend.{{ .Release.Namespace }}:80
            {{- range .Values.ingress.hosts }}
            - name: NEXT_PUBLIC_URL
              value: {{ .host }} 
            {{- end }}
    {{- with .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
    {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.frontend.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}
